#!/bin/bash

. "${top_srcdir-.}"/tests/common.sh

PPD="$(simple_ppd)"
function finish {
    rm -f "${PPD}"
}
trap finish EXIT

# Create a printer.
printf "CreatePrinter\n"
result=$(gdbus call --session \
	       --dest $PD_DEST \
	       --object-path $PD_PATH/Manager \
	       --method $PD_IFACE.Manager.CreatePrinter \
	       "{}" \
	       "updatedriver1" \
	       "printer description" \
	       "printer location" \
	       '["ipp://remote:631/printers/remote"]' \
	       "{}")

objpath=$(printf "%s" "$result" | sed -ne "s:^(objectpath '\(.*\)',):\1:p")
if [ -z "$objpath" ]; then
    printf "Expected (objectpath): %s\n" "$result"
    result_is 1
fi

# Update the driver with a specified driver-name
printf "UpdateDriver with driver-name\n"
result=$(gdbus call --session \
	       --dest $PD_DEST \
	       --object-path "$objpath" \
	       --method $PD_IFACE.Printer.UpdateDriver \
	       "{'driver-name':<'${PPD}'>}")
if [ "$result" != "()" ]; then
    printf "Expected (): %s\n" "$result"
    result_is 1
fi

# Verify the Driver property.
printf "Examining %s\n" "$objpath"
if ! diff -u - <(gdbus introspect --session --only-properties \
		       --dest $PD_DEST \
		       --object-path "$objpath" | \
			grep 's Driver = ' | LC_ALL=C sort | \
			sed -e 's,^ *readonly ,,') <<EOF
s Driver = '${PPD}';
EOF
then
  printf "Driver property differs from expected\n"
  result_is 1
fi

# Now delete it.
printf "DeletePrinter\n"
result=$(gdbus call --session \
	       --dest $PD_DEST \
	       --object-path $PD_PATH/Manager \
	       --method $PD_IFACE.Manager.DeletePrinter \
	       "{}" \
	       "$objpath")

if [ "$result" != "()" ]; then
    printf "Expected (): %s\n" "$result"
    result_is 1
fi

result_is 0
