#!/bin/bash

. "${top_srcdir-.}"/tests/common.sh

PID=$(cat "${top_builddir}/printerd-session.pid")
kill -INT "$PID"

RET=1
for i in 1 2 3 4 5; do
  sleep 1
  if kill -0 "$PID" 2>/dev/null; then :; else
    RET=0
    break
  fi
done

cat "${top_builddir}"/printerd-session.log
exit "$RET"
